### ISSUE TITLE
hi Can you submit a new pull request. I know a lot of new buildings which were developed. like Marina one. 9 straits view.. 

### ISSUE THREAD

**Issue by ptpmashish** [xkjyeah/singapore-postal-codes#1]
Please update the dump. cause a lot of new developments happened.

and thank you for the data. great help.

**Comment by xkjyeah** [comment]
Let me look into it

**Comment by ptpmashish** [comment]
Thanks man!

**Comment by xkjyeah** [comment]
Hey I've checked and Marina One is *in* the data dump. Which buildings are
you looking out for?

FYI I scrape OneMap daily. If you can find a building on OneMap.sg that you
cannot find here, then there's a bug in the scraping code. Otherwise, have
fun!

**Comment by ptpmashish** [comment]
Oh so this data is up to date  ? I thought its only till April 27 as mentioned in the description .

**Comment by ptpmashish** [comment]
read me file says 25 Apr 2017.

**Comment by xkjyeah** [comment]
Yup, just updated the README. I have a job on a server somewhere that updates the JSON every day. :D See the commit history :)
