### ISSUE TITLE
Hosting the JSON file as an API

### ISSUE THREAD

**Issue by ruchernchong** [xkjyeah/singapore-postal-codes#2]
Hi,

Are you planning to host the JSON file via GitHub pages or in anyway as an "API" for consuming?

**Comment by xkjyeah** [comment]
What do you want to use the API for?

My current assumption is that if you really needed Geocoding for a web app, you would use OneMap.sg's APi directly instead of loading the 60MB JSON ;)

If you have other use cases, let me know. Otherwise, you could also use rawgit.com

**Comment by ruchernchong** [comment]
I will check out OneMap's API then. Thanks!

Edit: I've just check OneMap's API. I guess I misunderstood something about this repository.
